#CI项目
name: JD-AX6600

#CI计划
on:
  #自动编译：每天早上4点
  # schedule:
  #   - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: 'PACKAGE: 手动调整插件包，仅限一个。'
        required: false
        type: string
        
      SOURCE:
        default: 'cmlong05/immortalwrt'
        required: true
        type: choice
        options: [cmlong05/immortalwrt, cmlong05/openwrt-kn, VIKINGYFY/immortalwrt, immortalwrt/immortalwrt, King-Of-Knights/openwrt-6.x, LiBwrt-op/openwrt-6.x]
      
      BRANCH:
        description: 'SOURCE BRANCH: default blank for main'
        required: false
        type: string
        
      TARGET: 
          default: 'IPQ60XX-WIFI-YES'
          required: true
          type: choice
          options: [IPQ60XX-WIFI-YES, IPQ60XX-WIFI-NO]
   
      
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.SOURCE}}/${{inputs.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        TARGET: [IPQ60XX-WIFI-YES]
        SOURCE: [King-Of-Knights/openwrt-6.x]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{inputs.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: LibWRT
      #默认WIFI名
      WRT_WIFI: LibWRT
      #默认地址
      WRT_IP: 192.168.1.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{inputs.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{inputs.BRANCH || 'main'}}
      #源码名称
      WRT_SOURCE: ${{inputs.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
